# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timeScaleDB:
  image:
  storage:
  secret:
    user: "postgres"
    password: "anyrandompassword"

api:
  image: ""
  replicas: ""
  test: ""