# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudProvider: "others"

sprinklerController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

waterController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

lightController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

controllerWorker:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  log:
    level: "info"
  replicas: 1
  HPA:
    enable: "true"
    minReplicas: 1
    maxReplicas: 2
    cpu:
      targetAverageUtilization: 10

api:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  replicas: 1
  log:
    level: "debug"
  ingress:
    enable: "false"
    host: ""

adminUI:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green-admin-ui:latest"
  replicas: 1
  imagePullPolicy: "Always"
  ingress:
    enable: "true"
    host: ""

timeScaleDB:
  image: "timescale/timescaledb:latest-pg11"
  persistent:
    enablePersistant: "true"
    storageClass: "default"
    volumeRequest: "1Gi"
  secret:
    user: "postgres"
    password: "anyrandompassword"

influxDB:
  image: "influxdb:1.8.3"
  persistent:
    enablePersistant: "true"
    storageClass: "default"
    volumeRequest: "1Gi"
  secret:
    user: "admin"
    password: "anyrandompassword"

telegraf:
  image: "telegraf:1.16.0"

mqtt:
  image: "docker.io/shanisma/eclipse-mosquitto:1.6.12"
  NodePort: 30181
  secret:
    user: "mqtt"
    password: "anyrandompassword"

grafana:
  persistence:
    enabled: true
    type: "pvc"
    size: "1Gi"
    storageClassName: "default"
  ingress:
    enabled: false
    annotations: { }
    labels: { }
    path: /
    hosts:
      - chart-example.local

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      storageClass: "default"
      size: "1Gi"
  slave:
    persistence:
      storageClass: "default"
      size: "1Gi"
