# Use for microk8s + ubuntu raspberry pi 4 deployment

cloudProvider: "microK8s"

sprinklerController:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green:arm-latest"
  imagePullPolicy: "Always"

waterController:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green:arm-latest"
  imagePullPolicy: "Always"

api:
  image: "docker.io/shanisma/k8s-one-green:arm-latest"
  imagePullPolicy: "Always"
  replicas: 1
  log:
    level: "debug"
  ingress:
    enable: "false"
    host: ""

timeScaleDB:
  image: "timescale/timescaledb:latest-pg11"
  persistent:
    enablePersistant: "true"
    storageClass: "microk8s-hostpath"
    volumeRequest: "1Gi"
  secret:
    user: "postgres"
    password: "anyrandompassword"

influxDB:
  image: "influxdb:1.8.3"
  persistent:
    enablePersistant: "true"
    storageClass: "microk8s-hostpath"
    volumeRequest: "1Gi"
  secret:
    user: "admin"
    password: "anyrandompassword"

telegraf:
  image: "telegraf:1.16.0"

mqtt:
  image: "docker.io/shanisma/eclipse-mosquitto:arm-latest"
  NodePort: 30181
  secret:
    user: "mqtt"
    password: "anyrandompassword"

grafana:
  persistence:
    enabled: true
    type: "pvc"
    size: "1Gi"
    storageClassName: "microk8s-hostpath"