# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timeScaleDB:
  image: "timescale/timescaledb:latest-pg11"
  persistent:
    enablePersistant: "true"
    storageClass: "default"
    volumeRequest: "1Gi"
  secret:
    user: "postgres"
    password: "anyrandompassword"

api:
  image: ""
  replicas: ""
  test: ""