# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sprinklers-controller:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green:latest"

water-controller:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green:latest"

api:
  image: "docker.io/shanisma/k8s-one-green:latest"
  imagePullPolicy: "IfNotPresent"
  replicas: "1"
  log:
    level: "debug"
  ingress:
    enable: "false"
    host: ""


timeScaleDB:
  image: "timescale/timescaledb:latest-pg11"
  persistent:
    enablePersistant: "true"
    storageClass: "default"
    volumeRequest: "1Gi"
  secret:
    user: "postgres"
    password: "anyrandompassword"

influxDB:
  image: "influxdb:1.8.3"
  persistent:
    enablePersistant: "true"
    storageClass: "default"
    volumeRequest: "1Gi"
  secret:
    user: "admin"
    password: "anyrandompassword"

telegraf:
  image: "telegraf:1.16.0"

mqtt:
  image: "docker.io/shanisma/eclipse-mosquitto:1.6.12"
  secret:
    user: "mqtt"
    password: "anyrandompassword"