# Use for microk8s + ubuntu raspberry pi 4 deployment

cloudProvider: "microK8s"

sprinklerController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

waterController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

lightController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

controllerWorker:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  log:
    level: "info"
  replicas: 1
  HPA:
    enable: "true"
    minReplicas: 1
    maxReplicas: 2
    cpu:
      targetAverageUtilization: 10

api:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  replicas: 1
  log:
    level: "debug"
  ingress:
    enable: "false"
    host: ""

adminUI:
  enable: "true"
  image: "docker.io/shanisma/k8s-one-green-admin-ui:latest"
  replicas: 1
  imagePullPolicy: "Always"
  ingress:
    enable: "true"
    host: ""

timeScaleDB:
  image: "timescale/timescaledb:latest-pg11"
  persistent:
    enablePersistant: "true"
    storageClass: "microk8s-hostpath"
    volumeRequest: "1Gi"
  secret:
    user: "postgres"
    password: "anyrandompassword"

influxDB:
  image: "influxdb:1.8.3"
  persistent:
    enablePersistant: "true"
    storageClass: "microk8s-hostpath"
    volumeRequest: "1Gi"
  secret:
    user: "admin"
    password: "anyrandompassword"

telegraf:
  image: "telegraf:1.16.0"

mqtt:
  image: "docker.io/shanisma/eclipse-mosquitto:1.6.12"
  NodePort: 30181
  secret:
    user: "mqtt"
    password: "anyrandompassword"

grafana:
  persistence:
    enabled: true
    type: "pvc"
    size: "1Gi"
    storageClassName: "microk8s-hostpath"
  ingress:
    enabled: false
  grafana.ini:
    server:
      # change 192.168.0.5 by your raspberry pi local IP or hostname
      root_url: "http://192.168.0.5/one-green-core-grafana/"
      serve_from_sub_path: true

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      storageClass: "microk8s-hostpath"
      size: "1Gi"
  slave:
    persistence:
      storageClass: "microk8s-hostpath"
      size: "1Gi"
