apiVersion: v2
name: one-green-core
description: One-Green Core deployment
type: application
version: 0.0.6
appVersion: 0.0.7
dependencies:
  - name: grafana
    version: 6.24.1
    repository: https://grafana.github.io/helm-charts
  - name: redis
    version: 16.8.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.1.13
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 8.31.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Shanmugathas Vigneswaran (github @shanisma)
    email: shanmugathas.vigneswaran@outlook.fr
    url: https://one-green.io
