apiVersion: v2
name: one-green-core
description: One-Green Core deployment
type: application
version: 0.0.7
appVersion: 0.0.10
dependencies:
  - name: grafana
    version: 6.29.6
    repository: https://grafana.github.io/helm-charts
  - name: redis
    version: 16.11.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 10.1.5
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Shanmugathas Vigneswaran (github @shanisma)
    email: shanmugathas.vigneswaran@outlook.fr
    url: https://one-green.io
