# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ogGlobal:
  microk8s:
    enableCustomIngress: false
  coreImage: &core_img docker.io/shanisma/og-core:0.0.4
  mqttImage: &mqtt_img docker.io/shanisma/eclipse-mosquitto:1.6.12
  telegrafImage: &telegraf_img telegraf:1.20.4
  storageClasse: &storage_class_name scw-bssd

sprinklerController:
  enable: "true"
  image: *core_img
  imagePullPolicy: "IfNotPresent"

waterController:
  enable: "true"
  image: *core_img
  imagePullPolicy: "IfNotPresent"

lightController:
  enable: "true"
  image: *core_img
  imagePullPolicy: "IfNotPresent"

celeryAsyncSharedWorker:
  image: *core_img
  imagePullPolicy: "IfNotPresent"
  log:
    level: "info"
  replicas: 1
  HPA:
    enable: "true"
    minReplicas: 1
    maxReplicas: 2
    cpu:
      targetAverageUtilization: 10

api:
  image: *core_img
  imagePullPolicy: "IfNotPresent"
  replicas: 3
  log:
    level: "info"
  ingress:
    enable: false
    host: ""

postgresql:
  global:
    postgresql:
      postgresqlUsername: "postgres"
      postgresqlPassword: "anyrandompassword"
    storageClass: *storage_class_name
  replication:
    readReplicas: 0
  persistence:
    size: "1Gi"
  image:
    pullPolicy: "IfNotPresent"

influxDB:
  image: "influxdb:2.0.8"
  persistent:
    enablePersistant: "true"
    storageClass: *storage_class_name
    volumeRequest: "1Gi"
  dataRetention: "1w"
  secret:
    user: "admin"
    password: "anyrandompassword"
    token: &influxdb_secret_token "change_this_token"

mqtt:
  image: *mqtt_img
  imagePullPolicy: IfNotPresent
  NodePort: 30181
  secret:
    user: mqtt
    password: anyrandompassword

telegraf:
  imagePullPolicy: IfNotPresent
  image: *telegraf_img

grafana:
  persistence:
    enabled: true
    type: "pvc"
    size: "1Gi"
    storageClassName: *storage_class_name
  ingress:
    enabled: false
    annotations: { }
    labels: { }
    path: /
    hosts:
      - chart-example.local
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: InfluxDB_v2_Flux
          type: influxdb
          access: proxy
          url: "http://{{ .Release.Name }}-influxdb:8086"
          secureJsonData:
            token: *influxdb_secret_token
          jsonData:
            version: Flux
            organization: "{{ .Release.Name }}"
            defaultBucket: "{{ .Release.Name }}-bucket"
            tlsSkipVerify: true

redis:
  auth:
    enabled: false
    sentinel: false
  master:
    persistence:
      storageClass: *storage_class_name
      size: "1Gi"
  replica:
    replicaCount: 0
    persistence:
      enabled: false
      storageClass: *storage_class_name
      size: "1Gi"
