# Default values for One-Green stack chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudProvider: "ScaleWay"

sprinklerController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

waterController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

lightController:
  enable: "true"
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"

controllerWorker:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  log:
    level: "info"
  replicas: 1
  HPA:
    enable: "true"
    minReplicas: 1
    maxReplicas: 2
    cpu:
      targetAverageUtilization: 10

api:
  image: "docker.io/shanisma/og-core:latest"
  imagePullPolicy: "Always"
  replicas: 1
  log:
    level: "debug"
  ingress:
    enable: "false"
    host: ""

adminUI:
  enable: "true"
  image: "docker.io/shanisma/og-admin:latest"
  replicas: 1
  imagePullPolicy: "Always"
  ingress:
    enable: "false"
    host: ""

postgresql:
  global:
    postgresql:
      postgresqlUsername: "postgres"
      postgresqlPassword: "anyrandompassword"
    storageClass: "scw-bssd"
  replication:
    readReplicas: 0
  persistence:
    size: "1Gi"
  image:
    pullPolicy: "IfNotPresent"

influxDB:
  image: "influxdb:2.0.8"
  persistent:
    enablePersistant: "true"
    storageClass: "scw-bssd"
    volumeRequest: "1Gi"
  dataRetention: "1w"
  secret:
    user: "admin"
    password: "anyrandompassword"
    token: "change_this_token"

telegraf:
  image: "telegraf:1.19.3"

mqtt:
  image: "docker.io/shanisma/eclipse-mosquitto:1.6.12"
  NodePort: 30181
  secret:
    user: "mqtt"
    password: "anyrandompassword"

grafana:
  persistence:
    enabled: true
    type: "pvc"
    size: "1Gi"
    storageClassName: "scw-bssd"
  ingress:
    enabled: false
    annotations: { }
    labels: { }
    path: /
    hosts:
      - chart-example.local

redis:
  auth:
    enabled: false
    sentinel: false
  master:
    persistence:
      storageClass: "scw-bssd"
      size: "1Gi"
  replica:
    replicaCount: 0
    persistence:
      enabled: false
      storageClass: "scw-bssd"
      size: "1Gi"
