apiVersion: v1
entries:
  one-green-core:
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2022-03-09T17:01:47.540391371+01:00"
    dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.24.0
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.5.0
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.4
    description: One-Green Core deployment
    digest: 0cd979b9a9cc2aa8ef90519f7bf50d0f79362fc912a9a82fc9f3767ae692bcf5
    maintainers:
    - email: shanmugathas.vigneswaran@outlook.fr
      name: Shanmugathas Vigneswaran (github @shanisma)
      url: https://one-green.io
    name: one-green-core
    type: application
    urls:
    - one-green-core-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-09T17:01:47.528484724+01:00"
    dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.18.1
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.6.3
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.13.11
    description: One-Green Core deployment
    digest: 8874988b2ef02e73703e0e12d8b7c014656a32d496dc0e2296b15d50e41befeb
    maintainers:
    - email: shanmugathas.vigneswaran@outlook.fr
      name: Shanmugathas Vigneswaran (github @shanisma)
      url: https://one-green.io
    name: one-green-core
    type: application
    urls:
    - one-green-core-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-09T17:01:47.516706889+01:00"
    dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.18.1
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.6.3
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.13.11
    description: One-Green Core deployment
    digest: 30fa943c903af2c23448f2ca8939334b9a628f4b29d16673feb3c57bc2144e0c
    maintainers:
    - email: shanmugathas.vigneswaran@outlook.fr
      name: Shanmugathas Vigneswaran (github @shanisma)
      url: https://one-green.io
    name: one-green-core
    type: application
    urls:
    - one-green-core-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-09T17:01:47.505172934+01:00"
    dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.16.9
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.10.2
    description: One-Green Core deployment
    digest: 58a91c85315598de208d465dc5240ff03764e42fda7fb934415191a75a1eb20b
    maintainers:
    - email: shanmugathas.vigneswaran@outlook.fr
      name: Shanmugathas Vigneswaran (github @shanisma)
      url: https://one-green.io
    name: one-green-core
    type: application
    urls:
    - one-green-core-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-09T17:01:47.493191688+01:00"
    dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.16.4
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    description: One-Green Core deployment
    digest: 816294f1f65c02f7957b98b0bed940c4258d01457cae8cd4abe8c4280e2a4178
    maintainers:
    - email: shanmugathas.vigneswaran@outlook.fr
      name: Shanmugathas Vigneswaran (github @shanisma)
      url: https://one-green.io
    name: one-green-core
    type: application
    urls:
    - one-green-core-0.0.1.tgz
    version: 0.0.1
generated: "2022-03-09T17:01:47.481844446+01:00"
