apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  # Set timezone UTC by default
  TZ: UTC
  # postgres configuration
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "one_green"
  # mqtt configuration
  MQTT_HOST: "{{ .Release.Name}}-mqtt"
  MQTT_PORT: "1883"
  # influxdb configuration
  INFLUXDB_HOST: "{{ .Release.Name }}-influxdb"
  INFLUXDB_PORT: "8086"
  INFLUXDB_URL: "http://{{ .Release.Name }}-influxdb:8086"
  DOCKER_INFLUXDB_INIT_MODE: setup  # create user authorisation without using web-ui
  DOCKER_INFLUXDB_INIT_ORG: "{{ .Release.Name }}"
  DOCKER_INFLUXDB_INIT_BUCKET: "{{ .Release.Name }}-bucket"
  DOCKER_INFLUXDB_INIT_RETENTION: "{{ .Values.influxDB.dataRetention }}"
  # REDIS (for Celery IoT async controller)
  REDIS_HOST: "{{ .Release.Name }}-redis-headless"
  REDIS_PORT: "6379"
  # Django config
  # internal service
  ONE_GREEN_API_HOST: "{{ .Release.Name }}-api"
  ONE_GREEN_API_PORT: "8080"
  ONE_GREEN_API_URL: "http://{{ .Release.Name }}-api:8080"
  # django settings.py
  CSRF_TRUSTED_ORIGINS: "https://{{ .Values.api.ingress.host }}"
  ALLOWED_HOSTS: {{ .Values.api.ingress.host | quote }}
  DEBUG: {{ .Values.api.django.debug | quote | lower }}
