apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  # postgres configuration
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql-headless"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "one_green"
  # mqtt configuration
  MQTT_HOST: "{{ .Release.Name}}-mqtt"
  MQTT_PORT: "1883"
  # influxdb configuration
  INFLUX_URL: "http://{{ .Release.Name }}-influxdb:8086"
  DOCKER_INFLUXDB_INIT_MODE: setup  # create user authorisation without using web-ui
  DOCKER_INFLUXDB_INIT_ORG: "{{ .Release.Name }}"
  DOCKER_INFLUXDB_INIT_BUCKET: "{{ .Release.Name }}-bucket"
  DOCKER_INFLUXDB_INIT_RETENTION: "{{ .Values.influxDB.dataRetention }}"
  # REDIS (for Celery IoT async controller)
  REDIS_HOST: "{{ .Release.Name }}-redis-headless"
  REDIS_PORT: "6379"
  # One-Green Api endpoint
  ONE_GREEN_CORE_API: "http://{{ .Release.Name }}-api:8080"
