{{/*Specific patch for microk8s ingress*/}}
{{ if eq .Values.ogGlobal.microk8s.enableCustomIngress true }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /{{ .Release.Name }}-grafana/
            backend:
              serviceName: {{ .Release.Name }}-grafana
              servicePort: 80
  {{ end }}
