{{ if eq .Values.lightController.enable "true" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-light-controller"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-light-controller"
  serviceName: "{{ .Release.Name }}-light-controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-light-controller"
      annotations:
        release.revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: light-controller
          image: "{{ .Values.lightController.image }}"
          command: [ '/bin/sh', '-c' ]
          args: [ 'cd light && python node_controller.py' ]
          imagePullPolicy: "{{ .Values.lightController.imagePullPolicy }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config"
            - secretRef:
                name:  "{{ .Release.Name }}-secrets"
          env:
            - name: "HEALTH_CHECK_TYPE"
              value: "redis,pg,mqtt"
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            exec:
              command:
                - python
                - health_check.py

  {{ end }}
