apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-mqtt
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/name: rabbitmq
  {{ if eq .Values.rabbitmqtNodePort.enable }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
    - port: 1883
      {{ if eq .Values.rabbitmqtNodePort.enable }}
      nodePort: {{ .Values.rabbitmqtNodePort.NodePort }}
      {{ end }}
