apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
data:
  # PostgreSQL db user and password definition
  POSTGRES_USER: "{{ .Values.postgresql.global.postgresql.postgresqlUsername | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}"
  # mqtt user and password definition
  MQTT_USERNAME: "{{ .Values.mqtt.secret.user | b64enc }}"
  MQTT_PASSWORD: "{{ .Values.mqtt.secret.password | b64enc }}"
  # influxdb
  DOCKER_INFLUXDB_INIT_USERNAME: "{{ .Values.influxDB.secret.user | b64enc }}"
  DOCKER_INFLUXDB_INIT_PASSWORD: "{{ .Values.influxDB.secret.password | b64enc }}"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ .Values.influxDB.secret.token | b64enc }}"
