{{ if eq .Values.sprinklerController.enable "true" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-sprinklers-controller"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-sprinklers-controller"
  serviceName: "{{ .Release.Name }}-sprinklers-controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-sprinklers-controller"
      annotations:
        release.revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: sprinklers-controller
          image: "{{ .Values.sprinklerController.image }}"
          command: [ '/bin/bash', '-c' ]
          args: [ 'cd sprinkler && python node_controller.py' ]
          imagePullPolicy: "{{ .Values.sprinklerController.imagePullPolicy }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config"
            - secretRef:
                name:  "{{ .Release.Name }}-secrets"
          env:
            - name: "HEALTH_CHECK_TYPE"
              value: "redis,pg,mqtt"
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            exec:
              command:
                - python
                - health_check.py

  {{ end }}
