apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-telegraf
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-telegraf
  serviceName: {{ .Release.Name }}-telegraf
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-telegraf
      annotations:
        release.revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: telegraf
          imagePullPolicy: {{ .Values.telegraf.imagePullPolicy }}
          image: {{ .Values.telegraf.image }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          volumeMounts:
            - name: conf
              mountPath: /etc/telegraf
      volumes:
        - name: conf
          configMap:
            name: {{ .Release.Name}}-telegraf-config
