apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name}}-telegraf-config"
data:
  # Configuration for
  # mqtt consumer to influx db sink
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "1s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      hostname = ""
      omit_hostname = false

    # output
    [[outputs.influxdb_v2]]
      urls = ["$INFLUXDB_URL"]
      token = "$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
      organization = "$DOCKER_INFLUXDB_INIT_ORG"
      bucket = "$DOCKER_INFLUXDB_INIT_BUCKET"

    # input influx line protocol format
    [[inputs.mqtt_consumer]]
       servers = ["tcp://$MQTT_HOST:1883"]
       topics = [
                  "water/sensor",
                  "sprinkler/sensor",
                  "cooler/sensor",
                  "heater/sensor",
                  "air_humidifier/sensor",
                ]
       qos = 0
       username = "$MQTT_USERNAME"
       password = "$MQTT_PASSWORD"
       data_format = "influx"
    # input json format
    [[inputs.mqtt_consumer]]
       name_override = "controllers"
       servers = ["tcp://$MQTT_HOST:1883"]
       topics = [
                  "water/controller/+",
                  "sprinkler/controller/+",
                  "cooler/controller/+",
                  "heater/controller/+",
                  "air_humidifier/controller/+"
                ]
       qos = 0
       username = "$MQTT_USERNAME"
       password = "$MQTT_PASSWORD"
       data_format = "json"
       tag_keys = [
        "controller_type",
        "tag"
        ]
