apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  # postgres configuration
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql-headless"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "one_green"
  # mqtt configuration
  MQTT_HOST: "{{ .Release.Name}}-mqtt"
  MQTT_PORT: "1883"
  # influxdb configuration
  INFLUX_HOST: "{{ .Release.Name }}-influxdb"
  INFLUX_PORT: "8086"
  INFLUXDB_DB: "one_green"
  INFLUXDB_HTTP_AUTH_ENABLED: "true"
  # REDIS (for Celery IoT async controller
  REDIS_HOST: "{{ .Release.Name }}-redis-headless"
  REDIS_PORT: "6379"
