apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name}}-mqtt"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name}}-mqtt"
  serviceName: "{{ .Release.Name}}-mqtt"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name}}-mqtt"
    spec:
      containers:
        - name: mqtt
          image: "{{ .Values.mqtt.image }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secrets"
          ports:
            - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name}}-mqtt"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ .Release.Name}}-mqtt"
  type: NodePort
  ports:
    - port: 1883
      nodePort: 30180
      name: mqtt
