apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-influxdb"
spec:
  serviceName: "{{ .Release.Name }}-influxdb"
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-influxdb"
  replicas: 1
  template:
    metadata:
      name: "{{ .Release.Name }}-influxdb"
      labels:
        app: "{{ .Release.Name }}-influxdb"
      annotations:
        release.revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: influxdb
          image: "{{ .Values.influxDB.image }}"
          env:
            - name: INFLUXDB_DB
              valueFrom:
                configMapKeyRef:
                  key: "INFLUXDB_DB"
                  name: "{{ .Release.Name }}-config"
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: "INFLUXDB_HTTP_AUTH_ENABLED"
                  name: "{{ .Release.Name }}-config"
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: INFLUXDB_ADMIN_USER
                  name: "{{ .Release.Name }}-secrets"
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: INFLUXDB_ADMIN_PASSWORD
                  name: "{{ .Release.Name }}-secrets"
          {{ if eq .Values.influxDB.persistent.enablePersistant "true"}}
          volumeMounts:
            - name: "{{ .Release.Name }}-influxdb-data"
              mountPath: /var/lib/influxdb
          {{ end }}
          ports:
            - containerPort: 8086
  {{ if eq .Values.influxDB.persistent.enablePersistant "true"}}
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Release.Name }}-influxdb-data"
      spec:
        storageClassName: "{{ .Values.influxDB.persistent.storageClass }}"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "{{ .Values.influxDB.persistent.volumeRequest }}"
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-influxdb"
spec:
  selector:
    app: "{{ .Release.Name }}-influxdb"
  ports:
    - port: 8086
  type: ClusterIP
