apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  # timescale db user and password definition
  POSTGRES_USER: "{{ .Values.timeScaleDB.secret.user | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.timeScaleDB.secret.password | b64enc }}"
  # mqtt user and password definition
  MOSQUITTO_USERNAME: "{{ .Values.mqtt.secret.user | b64enc }}"
  MOSQUITTO_PASSWORD: "{{ .Values.mqtt.secret.password | b64enc }}"
  # influxdb
  INFLUXDB_ADMIN_USER: "{{ .Values.influxDB.secret.user | b64enc }}"
  INFLUXDB_ADMIN_PASSWORD: "{{ .Values.influxDB.secret.password | b64enc }}"