apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
data:
  # PostgreSQL db user and password definition
  POSTGRES_USER: "{{ .Values.postgresql.global.postgresql.postgresqlUsername | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}"
  # mqtt user and password definition
  MOSQUITTO_USERNAME: "{{ .Values.mqtt.secret.user | b64enc }}"
  MOSQUITTO_PASSWORD: "{{ .Values.mqtt.secret.password | b64enc }}"
  # influxdb
  INFLUXDB_ADMIN_USER: "{{ .Values.influxDB.secret.user | b64enc }}"
  INFLUXDB_ADMIN_PASSWORD: "{{ .Values.influxDB.secret.password | b64enc }}"
