apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-tsdb"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tsdb"
  serviceName: "{{ .Release.Name }}-tsdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tsdb"
    spec:
      containers:
        - name: timescaledb
          image: "{{ .Values.timeScaleDB.image }} "
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secrets"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: conf
              mountPath: /etc/postgresql.conf
            {{ if eq .Values.timeScaleDB.persistent.enablePersistant "true" }}
            - name: "{{ .Release.Name }}-tsdb-data"
              mountPath: /var/lib/postgresql
            {{ end }}
      volumes:
        - name: conf
          configMap:
            name: "{{ .Release.Name }}-tsdb-conf"
  {{ if eq .Values.timeScaleDB.persistent.enablePersistant "true" }}
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Release.Name }}-tsdb-data"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.timeScaleDB.persistent.storageClass }}"
        resources:
          requests:
            storage: "{{ .Values.timeScaleDB.persistent.volumeRequest }}"
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-tsdb"
  namespace: "{{ .Release.Namespace }} "
spec:
  selector:
    app: "{{ .Release.Name }}-tsdb"
  ports:
    - port: 5432
  type: ClusterIP
